# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pierre/Documents/project/libft

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pierre/Documents/project/libft

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pierre/Documents/project/libft/CMakeFiles /home/pierre/Documents/project/libft//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pierre/Documents/project/libft/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ft

# Build rule for target.
ft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ft
.PHONY : ft

# fast build rule for target.
ft/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/build
.PHONY : ft/fast

src/ft_countc.o: src/ft_countc.c.o
.PHONY : src/ft_countc.o

# target to build an object file
src/ft_countc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_countc.c.o
.PHONY : src/ft_countc.c.o

src/ft_countc.i: src/ft_countc.c.i
.PHONY : src/ft_countc.i

# target to preprocess a source file
src/ft_countc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_countc.c.i
.PHONY : src/ft_countc.c.i

src/ft_countc.s: src/ft_countc.c.s
.PHONY : src/ft_countc.s

# target to generate assembly for a file
src/ft_countc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_countc.c.s
.PHONY : src/ft_countc.c.s

src/ft_isalpha.o: src/ft_isalpha.c.o
.PHONY : src/ft_isalpha.o

# target to build an object file
src/ft_isalpha.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_isalpha.c.o
.PHONY : src/ft_isalpha.c.o

src/ft_isalpha.i: src/ft_isalpha.c.i
.PHONY : src/ft_isalpha.i

# target to preprocess a source file
src/ft_isalpha.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_isalpha.c.i
.PHONY : src/ft_isalpha.c.i

src/ft_isalpha.s: src/ft_isalpha.c.s
.PHONY : src/ft_isalpha.s

# target to generate assembly for a file
src/ft_isalpha.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_isalpha.c.s
.PHONY : src/ft_isalpha.c.s

src/ft_isdigit.o: src/ft_isdigit.c.o
.PHONY : src/ft_isdigit.o

# target to build an object file
src/ft_isdigit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_isdigit.c.o
.PHONY : src/ft_isdigit.c.o

src/ft_isdigit.i: src/ft_isdigit.c.i
.PHONY : src/ft_isdigit.i

# target to preprocess a source file
src/ft_isdigit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_isdigit.c.i
.PHONY : src/ft_isdigit.c.i

src/ft_isdigit.s: src/ft_isdigit.c.s
.PHONY : src/ft_isdigit.s

# target to generate assembly for a file
src/ft_isdigit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_isdigit.c.s
.PHONY : src/ft_isdigit.c.s

src/ft_lstaddback.o: src/ft_lstaddback.c.o
.PHONY : src/ft_lstaddback.o

# target to build an object file
src/ft_lstaddback.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_lstaddback.c.o
.PHONY : src/ft_lstaddback.c.o

src/ft_lstaddback.i: src/ft_lstaddback.c.i
.PHONY : src/ft_lstaddback.i

# target to preprocess a source file
src/ft_lstaddback.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_lstaddback.c.i
.PHONY : src/ft_lstaddback.c.i

src/ft_lstaddback.s: src/ft_lstaddback.c.s
.PHONY : src/ft_lstaddback.s

# target to generate assembly for a file
src/ft_lstaddback.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_lstaddback.c.s
.PHONY : src/ft_lstaddback.c.s

src/ft_lstaddfront.o: src/ft_lstaddfront.c.o
.PHONY : src/ft_lstaddfront.o

# target to build an object file
src/ft_lstaddfront.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_lstaddfront.c.o
.PHONY : src/ft_lstaddfront.c.o

src/ft_lstaddfront.i: src/ft_lstaddfront.c.i
.PHONY : src/ft_lstaddfront.i

# target to preprocess a source file
src/ft_lstaddfront.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_lstaddfront.c.i
.PHONY : src/ft_lstaddfront.c.i

src/ft_lstaddfront.s: src/ft_lstaddfront.c.s
.PHONY : src/ft_lstaddfront.s

# target to generate assembly for a file
src/ft_lstaddfront.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_lstaddfront.c.s
.PHONY : src/ft_lstaddfront.c.s

src/ft_lstiteri.o: src/ft_lstiteri.c.o
.PHONY : src/ft_lstiteri.o

# target to build an object file
src/ft_lstiteri.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_lstiteri.c.o
.PHONY : src/ft_lstiteri.c.o

src/ft_lstiteri.i: src/ft_lstiteri.c.i
.PHONY : src/ft_lstiteri.i

# target to preprocess a source file
src/ft_lstiteri.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_lstiteri.c.i
.PHONY : src/ft_lstiteri.c.i

src/ft_lstiteri.s: src/ft_lstiteri.c.s
.PHONY : src/ft_lstiteri.s

# target to generate assembly for a file
src/ft_lstiteri.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_lstiteri.c.s
.PHONY : src/ft_lstiteri.c.s

src/ft_lstlast.o: src/ft_lstlast.c.o
.PHONY : src/ft_lstlast.o

# target to build an object file
src/ft_lstlast.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_lstlast.c.o
.PHONY : src/ft_lstlast.c.o

src/ft_lstlast.i: src/ft_lstlast.c.i
.PHONY : src/ft_lstlast.i

# target to preprocess a source file
src/ft_lstlast.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_lstlast.c.i
.PHONY : src/ft_lstlast.c.i

src/ft_lstlast.s: src/ft_lstlast.c.s
.PHONY : src/ft_lstlast.s

# target to generate assembly for a file
src/ft_lstlast.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_lstlast.c.s
.PHONY : src/ft_lstlast.c.s

src/ft_lstnew.o: src/ft_lstnew.c.o
.PHONY : src/ft_lstnew.o

# target to build an object file
src/ft_lstnew.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_lstnew.c.o
.PHONY : src/ft_lstnew.c.o

src/ft_lstnew.i: src/ft_lstnew.c.i
.PHONY : src/ft_lstnew.i

# target to preprocess a source file
src/ft_lstnew.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_lstnew.c.i
.PHONY : src/ft_lstnew.c.i

src/ft_lstnew.s: src/ft_lstnew.c.s
.PHONY : src/ft_lstnew.s

# target to generate assembly for a file
src/ft_lstnew.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_lstnew.c.s
.PHONY : src/ft_lstnew.c.s

src/ft_lstsize.o: src/ft_lstsize.c.o
.PHONY : src/ft_lstsize.o

# target to build an object file
src/ft_lstsize.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_lstsize.c.o
.PHONY : src/ft_lstsize.c.o

src/ft_lstsize.i: src/ft_lstsize.c.i
.PHONY : src/ft_lstsize.i

# target to preprocess a source file
src/ft_lstsize.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_lstsize.c.i
.PHONY : src/ft_lstsize.c.i

src/ft_lstsize.s: src/ft_lstsize.c.s
.PHONY : src/ft_lstsize.s

# target to generate assembly for a file
src/ft_lstsize.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_lstsize.c.s
.PHONY : src/ft_lstsize.c.s

src/ft_memcpy.o: src/ft_memcpy.c.o
.PHONY : src/ft_memcpy.o

# target to build an object file
src/ft_memcpy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_memcpy.c.o
.PHONY : src/ft_memcpy.c.o

src/ft_memcpy.i: src/ft_memcpy.c.i
.PHONY : src/ft_memcpy.i

# target to preprocess a source file
src/ft_memcpy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_memcpy.c.i
.PHONY : src/ft_memcpy.c.i

src/ft_memcpy.s: src/ft_memcpy.c.s
.PHONY : src/ft_memcpy.s

# target to generate assembly for a file
src/ft_memcpy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_memcpy.c.s
.PHONY : src/ft_memcpy.c.s

src/ft_memmove.o: src/ft_memmove.c.o
.PHONY : src/ft_memmove.o

# target to build an object file
src/ft_memmove.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_memmove.c.o
.PHONY : src/ft_memmove.c.o

src/ft_memmove.i: src/ft_memmove.c.i
.PHONY : src/ft_memmove.i

# target to preprocess a source file
src/ft_memmove.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_memmove.c.i
.PHONY : src/ft_memmove.c.i

src/ft_memmove.s: src/ft_memmove.c.s
.PHONY : src/ft_memmove.s

# target to generate assembly for a file
src/ft_memmove.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_memmove.c.s
.PHONY : src/ft_memmove.c.s

src/ft_memset.o: src/ft_memset.c.o
.PHONY : src/ft_memset.o

# target to build an object file
src/ft_memset.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_memset.c.o
.PHONY : src/ft_memset.c.o

src/ft_memset.i: src/ft_memset.c.i
.PHONY : src/ft_memset.i

# target to preprocess a source file
src/ft_memset.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_memset.c.i
.PHONY : src/ft_memset.c.i

src/ft_memset.s: src/ft_memset.c.s
.PHONY : src/ft_memset.s

# target to generate assembly for a file
src/ft_memset.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_memset.c.s
.PHONY : src/ft_memset.c.s

src/ft_putstrfd.o: src/ft_putstrfd.c.o
.PHONY : src/ft_putstrfd.o

# target to build an object file
src/ft_putstrfd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_putstrfd.c.o
.PHONY : src/ft_putstrfd.c.o

src/ft_putstrfd.i: src/ft_putstrfd.c.i
.PHONY : src/ft_putstrfd.i

# target to preprocess a source file
src/ft_putstrfd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_putstrfd.c.i
.PHONY : src/ft_putstrfd.c.i

src/ft_putstrfd.s: src/ft_putstrfd.c.s
.PHONY : src/ft_putstrfd.s

# target to generate assembly for a file
src/ft_putstrfd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_putstrfd.c.s
.PHONY : src/ft_putstrfd.c.s

src/ft_split.o: src/ft_split.c.o
.PHONY : src/ft_split.o

# target to build an object file
src/ft_split.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_split.c.o
.PHONY : src/ft_split.c.o

src/ft_split.i: src/ft_split.c.i
.PHONY : src/ft_split.i

# target to preprocess a source file
src/ft_split.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_split.c.i
.PHONY : src/ft_split.c.i

src/ft_split.s: src/ft_split.c.s
.PHONY : src/ft_split.s

# target to generate assembly for a file
src/ft_split.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_split.c.s
.PHONY : src/ft_split.c.s

src/ft_splitcs.o: src/ft_splitcs.c.o
.PHONY : src/ft_splitcs.o

# target to build an object file
src/ft_splitcs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_splitcs.c.o
.PHONY : src/ft_splitcs.c.o

src/ft_splitcs.i: src/ft_splitcs.c.i
.PHONY : src/ft_splitcs.i

# target to preprocess a source file
src/ft_splitcs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_splitcs.c.i
.PHONY : src/ft_splitcs.c.i

src/ft_splitcs.s: src/ft_splitcs.c.s
.PHONY : src/ft_splitcs.s

# target to generate assembly for a file
src/ft_splitcs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_splitcs.c.s
.PHONY : src/ft_splitcs.c.s

src/ft_toupper.o: src/ft_toupper.c.o
.PHONY : src/ft_toupper.o

# target to build an object file
src/ft_toupper.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_toupper.c.o
.PHONY : src/ft_toupper.c.o

src/ft_toupper.i: src/ft_toupper.c.i
.PHONY : src/ft_toupper.i

# target to preprocess a source file
src/ft_toupper.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_toupper.c.i
.PHONY : src/ft_toupper.c.i

src/ft_toupper.s: src/ft_toupper.c.s
.PHONY : src/ft_toupper.s

# target to generate assembly for a file
src/ft_toupper.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/src/ft_toupper.c.s
.PHONY : src/ft_toupper.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ft"
	@echo "... src/ft_countc.o"
	@echo "... src/ft_countc.i"
	@echo "... src/ft_countc.s"
	@echo "... src/ft_isalpha.o"
	@echo "... src/ft_isalpha.i"
	@echo "... src/ft_isalpha.s"
	@echo "... src/ft_isdigit.o"
	@echo "... src/ft_isdigit.i"
	@echo "... src/ft_isdigit.s"
	@echo "... src/ft_lstaddback.o"
	@echo "... src/ft_lstaddback.i"
	@echo "... src/ft_lstaddback.s"
	@echo "... src/ft_lstaddfront.o"
	@echo "... src/ft_lstaddfront.i"
	@echo "... src/ft_lstaddfront.s"
	@echo "... src/ft_lstiteri.o"
	@echo "... src/ft_lstiteri.i"
	@echo "... src/ft_lstiteri.s"
	@echo "... src/ft_lstlast.o"
	@echo "... src/ft_lstlast.i"
	@echo "... src/ft_lstlast.s"
	@echo "... src/ft_lstnew.o"
	@echo "... src/ft_lstnew.i"
	@echo "... src/ft_lstnew.s"
	@echo "... src/ft_lstsize.o"
	@echo "... src/ft_lstsize.i"
	@echo "... src/ft_lstsize.s"
	@echo "... src/ft_memcpy.o"
	@echo "... src/ft_memcpy.i"
	@echo "... src/ft_memcpy.s"
	@echo "... src/ft_memmove.o"
	@echo "... src/ft_memmove.i"
	@echo "... src/ft_memmove.s"
	@echo "... src/ft_memset.o"
	@echo "... src/ft_memset.i"
	@echo "... src/ft_memset.s"
	@echo "... src/ft_putstrfd.o"
	@echo "... src/ft_putstrfd.i"
	@echo "... src/ft_putstrfd.s"
	@echo "... src/ft_split.o"
	@echo "... src/ft_split.i"
	@echo "... src/ft_split.s"
	@echo "... src/ft_splitcs.o"
	@echo "... src/ft_splitcs.i"
	@echo "... src/ft_splitcs.s"
	@echo "... src/ft_toupper.o"
	@echo "... src/ft_toupper.i"
	@echo "... src/ft_toupper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

